---
- hosts: all
  environment: "{{proxy_settings}}"
  pre_tasks:
    - import_tasks: tasks/update.yml

  handlers:
    - import_tasks: handlers/grub.yml
    - import_tasks: handlers/patiobar.yml

  tasks:
    - import_tasks: tasks/repos.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/environment.yml
    - import_tasks: tasks/autologon.yml
    - import_tasks: tasks/autostart.yml
    - import_tasks: tasks/scripts.yml
    - import_tasks: tasks/grub.yml
    - import_tasks: tasks/motd.yml
    - import_tasks: tasks/patiobar.yml
    - import_tasks: tasks/pianobar_config.yml
