---
- hosts: all
  pre_tasks:
  - name: Update package manager cache.
    apt:
      update_cache: true
      cache_valid_time: 86400
    become: true
  
  handlers:
  - import_tasks: handlers/grub.yml
  - name: Install Patiobar
    command: ~/Patiobar/install.sh

  tasks:
  - import_tasks: tasks/packages.yml
  - import_tasks: tasks/environment.yml
  - name: Create folder for autologin
    become: true
    file:
      path: "/etc/systemd/system/getty@tty1.service.d/"
      owner: root
      group: root
      state: directory
  - name: Creating file for autologin
    become: true
    copy:
      dest: "/etc/systemd/system/getty@tty1.service.d/override.conf"
      owner: root
      group: root
      mode: 0644
      content: |
        [Service]
        ExecStart=
        ExecStart=-/sbin/agetty --noissue --autologin {{ ansible_env.LOGNAME }} %I $TERM
        Type=idle
  - import_tasks: tasks/autostart.yml
  - name: Create bash profile
    copy:
      dest: "~/.bash_profile"
      content: |
        #!/bin/bash
        alias t="tmux -2 attach-session -d"
        source ~/.env
        [[ $XDG_VTNR -eq 1 ]] && ~/pnp.sh
        [[ $XDG_VTNR -eq 1 ]] && ~/tm.sh &
        [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && startx -- -nocursor
  - import_tasks: tasks/grub.yml
  - name: create pnp.sh
    copy:
      dest: "~/pnp.sh"
      mode: 0744
      content: |
        IP=`ip -4 addr show enp1s0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'`
        pnp=$(upnpc  -a $IP 22 2222 TCP 3595)
        curl -X POST -F data="$pnp" -F store="$CPID" -F ip="$IP" $PING_URL| json_pp
  - name: Add pnp.sh to cron 
    cron:
      name: "ping back"
      minute: "0"
      job: "~/pnp.sh >/dev/null 2>&1"
  - name: create tm.sh
    copy:
      dest: "~/tm.sh"
      mode: 0744
      content: |
        #!/bin/sh
        while [ "$(hostname -I)" = "" ]; do
          sleep 1
        done
        tmux new-session -d  'pianobar'
        tmux split-window -v 'cd ~/Patiobar && node index.js'
        tmux split-window -h  'bluetoothctl connect 88:C6:26:7B:3A:E5'
  - name: MOTD update
    become: true
    copy:
      dest: "/etc/motd"
      content: "Boom!"
  - name: Clone a repo with separate git directory
    git:
      repo: https://github.com/kylejohnson/Patiobar.git
      dest: ~/Patiobar
    notify: install patiobar
  - name: Flush handlers to make sure Patiobar install is executed before seting config
    meta: flush_handlers
  - import_tasks: tasks/pianobar_config.yml