---
- name: Create folder for autologin
  become: true
  file:
    path: "/etc/systemd/system/getty@tty1.service.d/"
    owner: root
    group: root
    state: directory
- name: Creating file for autologin
  become: true
  template:
    dest: "/etc/systemd/system/getty@tty1.service.d/override.conf"
    owner: root
    group: root
    mode: 0644
    src: override.conf