---
- name: Create folder for autostart
  file:
    path: "~/.config/openbox"
    recurse: yes
    state: directory
- name: Creating file for autostart
  copy:
    dest: "~/.config/openbox/autostart"
    src: autostart