---
- name: Set Pandora User name
  lineinfile:
    dest: ~/.config/pianobar/config
    line: "user = {{env_dict.PANDORA_USER}}"
    regexp: "^user ="
    create: true
- name: Set Pandora password
  lineinfile:
    dest: ~/.config/pianobar/config
    line: "password = {{env_dict.PANDORA_PASS}}"
    regexp: "^password ="
