---
- name: Set Pandora User name 
  lineinfile:
    dest: ~/.config/pianobar/config
    line: "user = $PANDORA_USER"
    regexp: "^user ="
- name: Set Pandora password
  lineinfile:
      dest: ~/.config/pianobar/config
      line: "password = $PANDORA_PASS"
      regexp: "^password =" 